delete a single record
AnnaLangner/user_analysis pull request #8
Opened 2020-09-23 09:08 UTC by AnnaLangner

I wrote a script which removes the "picture " record from the json file

2020-09-23 17:47 UTC, klangner reviewed
There are no changes.

2020-09-27 10:38 UTC, AnnaLangner commented
Sorry, I think I missed something earlier

2020-10-01 06:58 UTC, klangner reviewed
Do not store binary file in the repo. Add content of /db to .gitignore

2020-10-01 06:58 UTC, klangner requested changes

2020-10-01 06:58 UTC, klangner commented on script/remove_record.py
> +def remove_record_from_json():
* Add main function
* Function should do 1 thing only
* do not use global variables

2020-10-11 17:07 UTC, klangner approved these changes

2020-10-12 07:19 UTC, merged